# Site settings
title: Paul Bird | Front-End Developer
email: paulbird1993@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-End Developer, Tinkerer and Currently Completing my
  Final Year as a BA(Hons) Digital Media Design Student at Bournemouth University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paulbird.co" # the base hostname & protocol for your site
twitter_username: birdyboy18
github_username:  birdyboy18

# Build settings
markdown: kramdown
highlighter: pygments
sass:
  style: compressed
